using System;
namespace Compi_I_Project.Core.Models
{
        public enum TokenType
        {
            Number,
            Boolean,
            String,
            Array,
            KwIf,
            KwElse,
            KwFor,
            KwWhile,
            KwIn,
            KwdDo,
            KwEnd,
            KwBegin,
            KwModule,
            KwElsif,
            KwDo,
            KwNext,
            KwAlias,
            kwNil,
            KwFalse,
            KwSuper,
            KwAnd,
            KwNot,
            KwEnsure,
            KwThen,
            KwUntil,
            KwBreak,
            KwRedo,
            KwWhen,
            KwCase,
            KwRescue,
            KwTrue,
            KwClass,
            KwRetry,
            KwUndef,
            KwDefined,
            KwDef,
            KwReturn,
            KwUnless,
            KwSelf,
            KwPuts,





            OpPlus,
            OpMinus,
            OpMul,
            OpDiv,
            OpMod,
            OpEOF,
            Unknown,
            Identifier,
            OpLessOrEqualThan,
            OpLessThan,
            OpGreaterOrEqualThan,
            OpGreaterThan,
            OpColon,
            OpSemicolon,
            OpLeftParens,
            OpRightParens,
            OpLeftBracket,
            OpRightBracket,
            OpLeftBrace,
            OpRightBrace,
            OpComma,
            OpEqual,
            OpAssignation,
            OpStringLiteral,
            OpLogicalAnd,
            OpLogicalOr,

        }
}
